name: Update and Deploy

on:
  schedule:
    - cron: '0 12 * * *'
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Python Script
        run: python scripts/xivapi_calls.py

      - name: Commit Changes
        run: |
          git config --global user.name "Daazed McFarland"
          git config --global user.email "daazedjmcfarland@gmail.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Automatic update"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
