name: Update and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive # Ensure submodules are updated

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --cached --name-only | grep -q "^.gitmodules$\|^scripts/craft-data"; then
            echo "Submodule-only changes detected."
            echo "continue_build=false" >> $GITHUB_ENV
          else
            echo "Changes beyond submodules detected."
            echo "continue_build=true" >> $GITHUB_ENV
          fi

      - name: Stop if only submodules updated
        if: env.continue_build == 'false'
        run: echo "Exiting as only submodules were updated." && exit 0

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

      # - name: Debug _site directory
      #   run: ls -R ./_site


  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
