name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python Script
        run: python ./scripts/xivapi_calls.py

      - name: Set up Jekyll Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Jekyll and Dependencies
        run: |
          gem install --user-install bundler
          echo 'export PATH="$HOME/.local/share/gem/ruby/3.0.0/bin:$PATH"' >> $GITHUB_ENV
          bundle config set --local path 'vendor/bundle'
          bundle install

      - name: Build Jekyll Site
        run: |
          bundle exec jekyll build

      - name: Fix File Permissions
        run: |
          chmod -c -R +rX ./_site | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Create Artifact
        run: |
          tar --dereference --hard-dereference --directory "./_site" -cvf "$RUNNER_TEMP/artifact.tar" --exclude=.git --exclude=.github .

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: "$RUNNER_TEMP/artifact.tar"
          retention-days: 1
